#!/usr/bin/env python3
"""Exact rational and orbit-data checker for the M6 strengthening.

No LP/MILP optimizer, floating-point bound, or numerical tolerance is used.
Maximal independent sets are regenerated by a separate Bron-Kerbosch routine.
"""
from pathlib import Path
from fractions import Fraction
from collections import Counter
import json
P=Path(__file__).resolve().parent

def make_graph():
 adj=[2,1]
 for _ in range(4):
  n=len(adj);new=[0]*(2*n+1)
  for i in range(n):
   for j in range(n):
    if adj[i]>>j&1:
     new[i]|=(1<<j)|(1<<(n+j));new[n+i]|=1<<j
   new[n+i]|=1<<(2*n);new[2*n]|=1<<(n+i)
  adj=new
 return adj

def maximal_sets(adj):
 n=len(adj);full=(1<<n)-1;comp=[full^(a|(1<<i)) for i,a in enumerate(adj)];out=[]
 def visit(R,P,X):
  if not P and not X:out.append(R);return
  possible=P|X
  pivot=max((i for i in range(n) if possible>>i&1),key=lambda i:(P&comp[i]).bit_count())
  choices=P&~comp[pivot]
  while choices:
   bit=choices&-choices;choices^=bit;v=bit.bit_length()-1
   visit(R|bit,P&comp[v],X&comp[v]);P^=bit;X|=bit
 visit(0,full,0)
 assert len(out)==len(set(out))
 return sorted(out)

adj=make_graph();N=len(adj);ALL=(1<<N)-1
assert N==47 and all(not(a>>i&1) for i,a in enumerate(adj))
assert all(bool(adj[i]>>j&1)==bool(adj[j]>>i&1) for i in range(N) for j in range(N))
assert all(not(adj[i]&adj[j]) for i in range(N) for j in range(i) if adj[i]>>j&1),'Triangle found'
MIS=maximal_sets(adj)
stored=json.loads((P.parent/'mycielski_pilot/m6_candidates.json').read_text())
assert adj==stored['adj'] and MIS==stored['candidate_masks'] and len(MIS)==857
for mask in MIS:
 assert all(not(adj[i]&mask) for i in range(N) if mask>>i&1)
 assert all(adj[i]&mask for i in range(N) if not(mask>>i&1))

cert=json.loads((P/'strengthening_certificates.json').read_text())
stats=Counter()

def f(n,d):
 assert isinstance(n,int) and isinstance(d,int) and d>0
 return Fraction(n,d)

def check(node,k,target,ones=0,zeros=0):
 assert not(ones&zeros) and not((ones|zeros)&~ALL)
 stats['nodes']+=1;kind=node['type'];stats[kind]+=1
 free=ALL&~(ones|zeros)
 if kind=='split':
  v=node['vertex'];assert isinstance(v,int) and 0<=v<N and free>>v&1
  check(node['zero'],k,target,ones,zeros|(1<<v))
  check(node['one'],k,target,ones|(1<<v),zeros)
  return
 if kind=='conflict':
  j=node['row'];assert 0<=j<len(MIS) and (MIS[j]&ones).bit_count()>k
  return
 if kind=='trivial':
  assert free==0 and node['bound']==ones.bit_count()<target
  return
 assert kind=='dual'
 y={};z={}
 for j,num,den in node['y']:
  assert 0<=j<len(MIS) and j not in y
  y[j]=f(num,den);assert y[j]>=0
 for v,num,den in node['z']:
  assert 0<=v<N and free>>v&1 and v not in z
  z[v]=f(num,den);assert z[v]>=0
 for v in range(N):
  if free>>v&1:
   covered=sum((w for j,w in y.items() if MIS[j]>>v&1),Fraction(0))+z.get(v,Fraction(0))
   assert covered>=1
 upper=Fraction(ones.bit_count())+sum((w*(k-(MIS[j]&ones).bit_count()) for j,w in y.items()),Fraction(0))+sum(z.values(),Fraction(0))
 assert upper==f(*node['bound']) and upper<target

expected={'non20_k3':(3,10,0,0),'non20_k9':(9,30,0,0),'non20_k12':(12,40,0,0),'apex_required':(6,20,0,1<<46)}
assert set(cert['certificates'])==set(expected)
for label,entry in cert['certificates'].items():
 k,target,ones,zeros=expected[label]
 assert (entry['k'],entry['forbidden_size'],entry['ones'],entry['zeros'])==(k,target,ones,zeros)
 check(entry['tree'],k,target,ones,zeros)
 print('PASS exact strengthening:',label)

cycle=[0,1,2,4,3];group=[]
for orientation in [1,-1]:
 for rotation in range(5):
  p=[0]*5
  for j,v in enumerate(cycle):p[v]=cycle[(orientation*j+rotation)%5]
  for _ in range(3):
   n=len(p);p=p+[n+i for i in p]+[2*n]
  group.append(p)
assert len({tuple(p) for p in group})==10
assert all(sorted(p)==list(range(47)) for p in group)
assert all(bool(adj[i]>>j&1)==bool(adj[p[i]]>>p[j]&1) for p in group for i in range(47) for j in range(47))
assert all(tuple(p[q[v]] for v in range(47)) in {tuple(g) for g in group} for p in group for q in group)
# Verify the hypotheses of the recursive automorphism-group argument.
a=[2,1]
for r in range(2,7):
 if r>=3:
  assert len(set(a))==len(a),'Open-neighborhood twins'
 if r>=4:
  degrees=[x.bit_count() for x in a]
  assert degrees[-1]>max(degrees[:-1]),'Apex is not unique maximum degree'
 if r==6:break
 n=len(a);b=[0]*(2*n+1)
 for i in range(n):b[i]=a[i]|(a[i]<<n);b[n+i]=a[i]|(1<<(2*n));b[2*n]|=1<<(n+i)
 a=b

def img(mask,p):return sum(1<<p[v] for v in range(47) if mask>>v&1)
D=json.loads((P/'complete_orbits.json').read_text())
recomputed=[int(s) for s in (P/'complete_orbit_representatives.txt').read_text().split()]
assert recomputed==sorted(recomputed) and len(set(recomputed))==len(recomputed)
assert recomputed==[o['representative'] for o in D['orbits']]
assert D['permutations']==group
allsets=set();layer=Counter();osizes=Counter()
for row in D['orbits']:
 W=row['representative'];orbit=sorted({img(W,p) for p in group})
 assert W==min(orbit) and row['orbit']==orbit and row['orbit_size']==len(orbit)
 assert W.bit_count()==20 and max((W&I).bit_count() for I in MIS)==6
 assert not(allsets&set(orbit));allsets.update(orbit)
 A=W&((1<<23)-1);B=(W>>23)&((1<<23)-1)
 assert W>>46==1 and A.bit_count()+B.bit_count()==19
 assert row['A']==[v for v in range(23) if A>>v&1]
 assert row['B']==[v for v in range(23) if B>>v&1]
 layer[(A.bit_count(),B.bit_count(),1)]+=1;osizes[len(orbit)]+=1
assert len(D['orbits'])==199 and len(allsets)==1990
assert layer=={(13,6,1):109,(14,5,1):83,(15,4,1):7}
assert osizes=={10:199}
result={'status':'PASS','rational_certificate_nodes':dict(stats),'orbit_count':199,'labelled_extremizers':1990,'orbit_sizes':dict(osizes),'orbit_layer_counts':{str(k):v for k,v in sorted(layer.items())},'automorphism_group':'D5 of order10; structural hypotheses checked','enumeration_completeness':'Requires exact enumerate_extremizers.cpp run; this checker matches its regenerated representatives to stored orbit data','scope':'Ambient-automorphism orbits, not abstract induced-graph isomorphism classes'}
(P/'strengthening_check.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps(result,indent=2))
