import Lean.Util.Path
import TargetA.AllTheorems
import TargetA.Period8ConjectureConstant
import TargetA.R2FourteenthStepCertificate

#print axioms TargetA.residueZero_mod
#print axioms TargetA.residueZero_even
#print axioms TargetA.residueZero_admissible
#print axioms TargetA.dft_cellTranslation
#print axioms TargetA.stdAddChar_pow_modulus
#print axioms TargetA.cell_reindex_forward
#print axioms TargetA.cell_reindex_unindex
#print axioms TargetA.cell_unindex_next_one_interior
#print axioms TargetA.cell_unindex_next_two_interior
#print axioms TargetA.cell_unindex_next_one_seam
#print axioms TargetA.cell_unindex_next_two_seam_six
#print axioms TargetA.cell_unindex_next_two_seam_seven
#print axioms TargetA.cell_unindex_next_one
#print axioms TargetA.cell_unindex_next_two
#print axioms TargetA.period8_forward_reindex_action
#print axioms TargetA.period8_forward_reindex_actionC
#print axioms TargetA.zmod_finEquiv_eq_natCast
#print axioms TargetA.zmod_finEquiv_cyclic_next
#print axioms TargetA.zmod_finEquiv_cyclic_prev
#print axioms TargetA.cell_zmod_reindex_residue
#print axioms TargetA.cyclic_next_prev
#print axioms TargetA.cyclic_prev_next
#print axioms TargetA.cyclic_next_eq_iff
#print axioms TargetA.hamilton_gauge_matrix_eq_forward_add_transpose
#print axioms TargetA.hamilton_gauge_forward_matrix_mulVec
#print axioms TargetA.hamilton_gauge_forward_matrixC_mulVec
#print axioms TargetA.hamilton_gauge_matrix_symmetric
#print axioms TargetA.hamilton_gauge_matrix_zero_of_not_neighbour
#print axioms TargetA.cyclic_next_one_ne_self
#print axioms TargetA.cyclic_next_two_ne_self
#print axioms TargetA.cyclic_next_one_then_one
#print axioms TargetA.cyclic_next_one_ne_two
#print axioms TargetA.hamilton_gauge_matrix_diagonal_zero
#print axioms TargetA.period_eight_value_is_sign
#print axioms TargetA.forward_step_one_is_sign
#print axioms TargetA.forward_step_two_is_sign
#print axioms TargetA.forward_step_one_periodic_holonomy
#print axioms TargetA.forward_step_two_periodic_holonomy
#print axioms TargetA.period_eight_repeat
#print axioms TargetA.period8_target_lift_cell_value
#print axioms TargetA.period8_target_tau_is_sign
#print axioms TargetA.period8_target_lift_is_sign
#print axioms TargetA.period8_target_lift_periodic
#print axioms TargetA.period8_target_step_two_is_sign
#print axioms TargetA.period8_target_step_one_is_sign
#print axioms TargetA.period8_target_matrix_symmetric
#print axioms TargetA.period8_target_matrix_isHermitian
#print axioms TargetA.period8_target_matrix_diagonal_zero
#print axioms TargetA.step_one_cut_rule
#print axioms TargetA.step_two_cut_rule
#print axioms TargetA.step_one_no_cut
#print axioms TargetA.step_one_cut
#print axioms TargetA.step_two_no_cut
#print axioms TargetA.step_two_cut
#print axioms TargetA.period_eight_fits_multiple
#print axioms TargetA.period8_raw_to_cell_injective
#print axioms TargetA.period8_raw_to_cell_intertwines
#print axioms TargetA.zmod_finEquiv_cyclic_step
#print axioms TargetA.period8_double_cell_shift_unindex
#print axioms TargetA.period8_raw_half_shift_to_cell_antiperiodic
#print axioms TargetA.period8_double_cover_antisector_eigen_square_lt_edge
#print axioms TargetA.period8_antiperiodic_parameter_re_lt_two
#print axioms TargetA.period8_antiperiodic_holonomy_root_lt_edge
#print axioms TargetA.period8_antiperiodic_fiber_eigen_square_lt_edge
#print axioms TargetA.period8_antiperiodic_nonzero_dft_holonomy
#print axioms TargetA.period8_antiperiodic_cell_eigen_square_lt_edge
#print axioms TargetA.period8_intra_as_forward_add_transpose
#print axioms TargetA.period8_backward_is_forward_transpose
#print axioms TargetA.period8_cell_action_fin_eq_forward_add_backward
#print axioms TargetA.period8_forward_cell_operator_fin_apply
#print axioms TargetA.period8_forward_reindex_actionC_eq_cell_operator
#print axioms TargetA.period8_forward_cell_matrix_fin_mulVec
#print axioms TargetA.period8_forward_cell_matrix_fin_transpose_mulVec
#print axioms TargetA.period8_cell_matrix_fin_mulVec
#print axioms TargetA.period8_reindexed_forward_matrix_mulVec
#print axioms TargetA.period8_reindexed_forward_matrix_eq_cell_matrix
#print axioms TargetA.period8_reindexed_matrix_eq_forward_add_transpose
#print axioms TargetA.period8_reindexed_matrix_eq_cell_matrix
#print axioms TargetA.period8_reindexed_matrix_mulVec
#print axioms TargetA.period8_reindexed_forward_operator_eq
#print axioms TargetA.period8_fiber_as_cell_symbol
#print axioms TargetA.period8_cell_dft_translation
#print axioms TargetA.period8_cell_dft_matrix
#print axioms TargetA.cellEncode_rawToFinCell
#print axioms TargetA.period8_reindexed_matrix_mulVec_raw
#print axioms TargetA.period8_fin_cell_action_to_zmod
#print axioms TargetA.exists_nonzero_period8_cell_dft
#print axioms TargetA.period8_cell_dft_action
#print axioms TargetA.period8_cell_eigen_dft_fiber
#print axioms TargetA.period8_zmod_real_eigen_square_lt_bound
#print axioms TargetA.period8_raw_real_eigen_square_lt_bound
#print axioms TargetA.period8_target_eigenvalue_square_lt_bound
#print axioms TargetA.period8_target_eigenvalue_beats_twisted
#print axioms TargetA.period8_alpha_plus_main_theorem
#print axioms TargetA.period8_chiral_determinant_complex
#print axioms TargetA.period8_unit_conj_eq_inv
#print axioms TargetA.period8_unit_of_pow_eq_one
#print axioms TargetA.period8_xi_unit_from_holonomy
#print axioms TargetA.period8_unit_parameter_real
#print axioms TargetA.period8_unit_parameter_re_le_two
#print axioms TargetA.period8_polynomialC_ofReal
#print axioms TargetA.period8_complex_root_is_real_root
#print axioms TargetA.period8_unit_complex_root_is_real_root
#print axioms TargetA.period8_unit_complex_root_lt_bound
#print axioms TargetA.period8_holonomy_root_lt_bound
#print axioms TargetA.period8_squared_chiral_block
#print axioms TargetA.period8_squared_block_annihilated
#print axioms TargetA.period8_matrix_power_on_eigenvector
#print axioms TargetA.period8_squared_block_eigen_root
#print axioms TargetA.period8_squared_block_eigen_lt_bound
#print axioms TargetA.period8_chiral_determinant
#print axioms TargetA.period8_endpoint_quartic_factorization
#print axioms TargetA.period8_conjecture_constant_square
#print axioms TargetA.period8_conjecture_constant_nonneg
#print axioms TargetA.period8_negative_argument_polynomial_pos
#print axioms TargetA.period8_conjecture_constant_is_root
#print axioms TargetA.period8_conjecture_constant_greatest_root
#print axioms TargetA.period8_conjecture_constant_largest_real_root
#print axioms TargetA.period8_alpha_minus_eigenvalue_abs_lt_conjecture_constant
#print axioms TargetA.period8_conjecture28_strict_family
#print axioms TargetA.period8_double_lift_low
#print axioms TargetA.period8_double_lift_high
#print axioms TargetA.period8_double_lift_injective
#print axioms TargetA.period8_double_low_half_shift
#print axioms TargetA.period8_double_high_half_shift
#print axioms TargetA.period8_double_lift_antiperiodic
#print axioms TargetA.period8_double_same_half_next
#print axioms TargetA.period8_double_cross_half_next
#print axioms TargetA.period8_double_signed_forward_entry
#print axioms TargetA.period8_double_low_lift
#print axioms TargetA.period8_double_high_lift
#print axioms TargetA.period8_periodic_matrix_entry
#print axioms TargetA.period8_double_matrix_same_blocks
#print axioms TargetA.period8_double_matrix_cross_blocks
#print axioms TargetA.period8_double_matrix_difference
#print axioms TargetA.period8_sum_double
#print axioms TargetA.period8_double_matrixC_difference
#print axioms TargetA.period8_double_matrixC_same_blocks
#print axioms TargetA.period8_double_matrixC_cross_blocks
#print axioms TargetA.period8_double_action_low
#print axioms TargetA.period8_double_action_high
#print axioms TargetA.period8_double_lift_intertwines
#print axioms TargetA.period8_double_lift_smul
#print axioms TargetA.period8_alpha_minus_raw_eigen_square_lt_edge
#print axioms TargetA.period8_alpha_minus_main_theorem
#print axioms TargetA.period8_finite_top_pos
#print axioms TargetA.period8_unit_parameter_eq_two_re
#print axioms TargetA.period8_alpha_minus_raw_eigen_square_le_finite_top
#print axioms TargetA.period8_alpha_minus_finite_radius_attained_vector
#print axioms TargetA.period8_hermitian_eigenvector_has_index
#print axioms TargetA.period8_alpha_minus_eigenvalue_square_le_finite_top
#print axioms TargetA.period8_alpha_minus_finite_radius_attained_index
#print axioms TargetA.period8_finite_radius_radical
#print axioms TargetA.period8_alpha_minus_exact_finite_radius
#print axioms TargetA.period8_polynomial_shift_identity
#print axioms TargetA.period8_inner_discriminant_pos
#print axioms TargetA.period8_inner_sqrt_ge_four
#print axioms TargetA.period8_top_radicand_pos
#print axioms TargetA.period8_top_root_gt_four
#print axioms TargetA.period8_top_root_is_root
#print axioms TargetA.period8_root_le_top_root
#print axioms TargetA.period8_top_radicand_strict_mono
#print axioms TargetA.period8_top_root_strict_mono
#print axioms TargetA.period8_top_root_at_two
#print axioms TargetA.period8_chiral_square
#print axioms TargetA.period8_chiral_anticommutes
#print axioms TargetA.period8_chiral_maps_plus_to_minus
#print axioms TargetA.period8_chiral_basis_left_inverse
#print axioms TargetA.period8_chiral_basis_right_inverse
#print axioms TargetA.period8_xi_mul_inv_sq
#print axioms TargetA.period8_inv_sq_mul_xi
#print axioms TargetA.period8_xi_mul_inv
#print axioms TargetA.period8_fiber_in_chiral_basis
#print axioms TargetA.period8_fiber_similar_to_chiral_coordinates
#print axioms TargetA.period8_complex_squared_block
#print axioms TargetA.period8_complex_squared_block_annihilated
#print axioms TargetA.period8_complex_matrix_power_on_eigenvector
#print axioms TargetA.period8_complex_squared_block_eigen_root
#print axioms TargetA.period8_top_project_embed
#print axioms TargetA.period8_bottom_project_embed
#print axioms TargetA.period8_top_project_bottom_embed
#print axioms TargetA.period8_bottom_project_top_embed
#print axioms TargetA.period8_embed_project_reconstruct
#print axioms TargetA.period8_chiral_top_action
#print axioms TargetA.period8_chiral_bottom_action
#print axioms TargetA.period8_chiral_coordinate_action
#print axioms TargetA.period8_chiral_top_equation
#print axioms TargetA.period8_chiral_bottom_equation
#print axioms TargetA.period8_chiral_top_nonzero
#print axioms TargetA.period8_chiral_squared_top_eigen
#print axioms TargetA.period8_chiral_eigen_square_root
#print axioms TargetA.period8_fiber_inverse_intertwines
#print axioms TargetA.period8_fiber_eigen_square_root
#print axioms TargetA.period8_fiber_polynomialC_eq
#print axioms TargetA.period8_fiber_real_eigen_square_lt_bound
#print axioms TargetA.period8_fiber_isHermitian
#print axioms TargetA.period8_squared_block_characteristic_det
#print axioms TargetA.period8_root_gives_squared_block_eigenvector
#print axioms TargetA.period8_squared_eigenvector_gives_chiral_eigenvector
#print axioms TargetA.period8_polynomial_root_gives_fiber_eigenvector
#print axioms TargetA.period8_unit_parameter_mem_interval
#print axioms TargetA.period8_unit_fiber_eigen_square_le_top
#print axioms TargetA.period8_unit_fiber_top_attained
#print axioms TargetA.period8_std_char_re
#print axioms TargetA.period8_nonzero_phase_re_le_first
#print axioms TargetA.period8_antiperiodic_phase_re_le_first
#print axioms TargetA.period8_first_phase_antiperiodic
#print axioms TargetA.period8_first_phase_re
#print axioms TargetA.period8_bound_positive
#print axioms TargetA.period8_boundary_factorization
#print axioms TargetA.period8_edge_is_boundary_root
#print axioms TargetA.period8_at_two_positive
#print axioms TargetA.period8_polynomial_monotone_in_flux
#print axioms TargetA.period8_polynomial_positive
#print axioms TargetA.period8_root_lt_bound
#print axioms TargetA.period8_cell_to_raw_right_inverse
#print axioms TargetA.period8_raw_to_cell_smul
#print axioms TargetA.period8_cell_eigen_gives_raw_periodic_eigen
#print axioms TargetA.period8_cell_antiperiodic_gives_raw_half_shift
#print axioms TargetA.period8_half_shift_is_double_lift
#print axioms TargetA.period8_antiperiodic_cell_eigen_gives_raw_minus_eigenvector
#print axioms TargetA.period8_first_plane_wave_nonzero
#print axioms TargetA.period8_first_plane_wave_action
#print axioms TargetA.period8_first_plane_wave_antiperiodic
#print axioms TargetA.period8_first_fiber_eigen_gives_raw_minus_eigenvector
#print axioms TargetA.period8_edge_lt_bound
#print axioms TargetA.period8_edge_ge_fifteen_halves
#print axioms TargetA.period8_edge_quadratic
#print axioms TargetA.period8_at_two_nonneg_of_edge_le
#print axioms TargetA.period8_at_two_pos_of_edge_lt
#print axioms TargetA.period8_flux_factor_pos
#print axioms TargetA.period8_polynomial_ge_at_two_of_edge_le
#print axioms TargetA.period8_polynomial_pos_of_edge_le_flux_lt
#print axioms TargetA.period8_root_lt_edge
#print axioms TargetA.period8_root_le_edge
#print axioms TargetA.period8_edge_root_iff
#print axioms TargetA.gapCharge_mod_four
#print axioms TargetA.sector_after_gap
#print axioms TargetA.r2_seed106_ldl_rat
#print axioms TargetA.r2_seed106_lower_rat
#print axioms TargetA.r2_seed106_lower_diagonal_rat
#print axioms TargetA.r2_seed106_diagonal_pos_rat
#print axioms TargetA.r2_seed106_ldl_real
#print axioms TargetA.r2_seed106_diagonal_pos
#print axioms TargetA.r2_seed106_lower_triangular
#print axioms TargetA.r2_seed106_lower_diagonal
#print axioms TargetA.r2_seed106_lower_det
#print axioms TargetA.r2_seed106_margin_posDef
#print axioms TargetA.r2_posDef_submatrix_equiv
#print axioms TargetA.r2_strict_schur_criterion
#print axioms TargetA.r2_terminal_posDef_iff
#print axioms TargetA.r2_terminal_core_blocks
#print axioms TargetA.r2_terminal_core_symmetric_blocks
#print axioms TargetA.r2_terminal_cross_correction
#print axioms TargetA.r2_terminal_H_corrections
#print axioms TargetA.r2_terminal_EPlus_posDef_iff
#print axioms TargetA.twisted_block_symmetric
#print axioms TargetA.twisted_block_trace_zero
#print axioms TargetA.twisted_block_characteristic
#print axioms TargetA.sqrt_two_gt_141_over_100
#print axioms TargetA.sqrt_two_add_sqrt_two_gt_923_over_500
#print axioms TargetA.sqrt_two_add_nested_gt_1961_over_1000
#print axioms TargetA.twisted_at_thirty_two_gt_bound
#print axioms TargetA.twisted_multiple_of_eight_gt_bound
#check TargetA.r2_seed106_ldl_rat
#check TargetA.r2_seed106_diagonal_pos_rat
#check TargetA.r2_seed106_lower_det
#check TargetA.r2_seed106_margin_posDef
#check TargetA.r2_terminal_EPlus_posDef_iff


#print axioms TargetA.r2_orbit_eq_of_certificates
#print axioms TargetA.r2_core_with_actual_inverse_eq_terminal
#print axioms TargetA.r2_recurrence_terminal_posDef_iff
#print axioms TargetA.r2_core26_eq_of_certificates
#print axioms TargetA.r2_core26_margin_of_seed_certificate

#print axioms TargetA.r2_real_matrix_add
#print axioms TargetA.r2_real_matrix_sub
#print axioms TargetA.r2_real_matrix_neg
#print axioms TargetA.r2_real_matrix_mul
#print axioms TargetA.r2_real_matrix_transpose
#print axioms TargetA.r2_real_matrix_one
#print axioms TargetA.r2_real_matrix_submatrix
#print axioms TargetA.r2_real_matrix_fromBlocks
#print axioms TargetA.r2_real_D
#print axioms TargetA.r2_real_EP
#print axioms TargetA.r2_real_EM
#print axioms TargetA.r2_real_coupling
#print axioms TargetA.r2_real_initial
#print axioms TargetA.r2_real_update
#print axioms TargetA.r2_real_inverse_of_certificate
#print axioms TargetA.r2_pivot_isUnit_of_certificate
#print axioms TargetA.r2_real_core_with_inverse
#print axioms TargetA.r2_real_orbit_eq_of_certificates
#print axioms TargetA.r2_real_core26_eq_of_certificates
#print axioms TargetA.r2_core26_margin_of_rational_seed_certificate

#print axioms TargetA.r2_adjugate_two_identity
#print axioms TargetA.r2_inverse_two_formula
#print axioms TargetA.r2_pair_lift_mul
#print axioms TargetA.r2_pair_lift_one
#print axioms TargetA.r2_pair_lift_two
#print axioms TargetA.r2_first_integer_determinant
#print axioms TargetA.r2_first_integer_adjugate_product
#print axioms TargetA.r2_first_denominator_clearing
#print axioms TargetA.r2_first_scaled_product
#print axioms TargetA.r2_first_scaled_pivot_entries
#print axioms TargetA.r2_first_scaled_adjugate_entries
#print axioms TargetA.r2_first_pivot_pair_lift
#print axioms TargetA.r2_first_inverse_pair_lift
#print axioms TargetA.r2_first_inverse_product
#print axioms TargetA.r2_first_actual_inverse
#print axioms TargetA.r2_first_actual_real_inverse

#print axioms TargetA.r2_first_recorded_initial
#print axioms TargetA.r2_first_transition_X
#print axioms TargetA.r2_first_transition_R
#print axioms TargetA.r2_first_transition_W
#print axioms TargetA.r2_first_transition_G
#print axioms TargetA.r2_first_transition_H
#print axioms TargetA.r2_first_transition_C
#print axioms TargetA.r2_first_recorded_transition
#print axioms TargetA.r2_first_actual_orbit
#print axioms TargetA.r2_first_actual_real_orbit

#print axioms TargetA.r2_mul_four_apply
#print axioms TargetA.r2_second_inverse_product
#print axioms TargetA.r2_second_actual_inverse
#print axioms TargetA.r2_second_actual_real_inverse
#print axioms TargetA.r2_second_transition_X
#print axioms TargetA.r2_second_transition_R
#print axioms TargetA.r2_second_transition_W
#print axioms TargetA.r2_second_transition_G
#print axioms TargetA.r2_second_transition_H
#print axioms TargetA.r2_second_transition_C
#print axioms TargetA.r2_second_recorded_transition
#print axioms TargetA.r2_second_actual_orbit
#print axioms TargetA.r2_second_actual_real_orbit

#print axioms TargetA.r2_third_inverse_product
#print axioms TargetA.r2_third_actual_inverse
#print axioms TargetA.r2_third_actual_real_inverse
#print axioms TargetA.r2_third_transition_X
#print axioms TargetA.r2_third_transition_R
#print axioms TargetA.r2_third_transition_W
#print axioms TargetA.r2_third_transition_G
#print axioms TargetA.r2_third_transition_H
#print axioms TargetA.r2_third_transition_C
#print axioms TargetA.r2_third_recorded_transition
#print axioms TargetA.r2_third_actual_orbit
#print axioms TargetA.r2_third_actual_real_orbit

#print axioms TargetA.r2_fourth_inverse_product
#print axioms TargetA.r2_fourth_actual_inverse
#print axioms TargetA.r2_fourth_actual_real_inverse
#print axioms TargetA.r2_fourth_transition_X
#print axioms TargetA.r2_fourth_transition_R
#print axioms TargetA.r2_fourth_transition_W
#print axioms TargetA.r2_fourth_transition_G
#print axioms TargetA.r2_fourth_transition_H
#print axioms TargetA.r2_fourth_transition_C
#print axioms TargetA.r2_fourth_recorded_transition
#print axioms TargetA.r2_fourth_actual_orbit
#print axioms TargetA.r2_fourth_actual_real_orbit

#print axioms TargetA.r2_fifth_inverse_product
#print axioms TargetA.r2_fifth_actual_inverse
#print axioms TargetA.r2_fifth_actual_real_inverse
#print axioms TargetA.r2_fifth_transition_X
#print axioms TargetA.r2_fifth_transition_R
#print axioms TargetA.r2_fifth_transition_W
#print axioms TargetA.r2_fifth_transition_G
#print axioms TargetA.r2_fifth_transition_H
#print axioms TargetA.r2_fifth_transition_C
#print axioms TargetA.r2_fifth_recorded_transition
#print axioms TargetA.r2_fifth_actual_orbit
#print axioms TargetA.r2_fifth_actual_real_orbit

#print axioms TargetA.r2_sixth_inverse_product
#print axioms TargetA.r2_sixth_actual_inverse
#print axioms TargetA.r2_sixth_actual_real_inverse
#print axioms TargetA.r2_sixth_transition_X
#print axioms TargetA.r2_sixth_transition_R
#print axioms TargetA.r2_sixth_transition_W
#print axioms TargetA.r2_sixth_transition_G
#print axioms TargetA.r2_sixth_transition_H
#print axioms TargetA.r2_sixth_transition_C
#print axioms TargetA.r2_sixth_recorded_transition
#print axioms TargetA.r2_sixth_actual_orbit
#print axioms TargetA.r2_sixth_actual_real_orbit

#eval do IO.println s!"RESOLVED_STEP6={← Lean.findOLean `TargetA.R2SixthStepCertificate}"
#eval do IO.println s!"RESOLVED_STEP5={← Lean.findOLean `TargetA.R2FifthStepCertificate}"

#print axioms TargetA.r2_seventh_inverse_product
#print axioms TargetA.r2_seventh_actual_inverse
#print axioms TargetA.r2_seventh_actual_real_inverse
#print axioms TargetA.r2_seventh_transition_X
#print axioms TargetA.r2_seventh_transition_R
#print axioms TargetA.r2_seventh_transition_W
#print axioms TargetA.r2_seventh_transition_G
#print axioms TargetA.r2_seventh_transition_H
#print axioms TargetA.r2_seventh_transition_C
#print axioms TargetA.r2_seventh_recorded_transition
#print axioms TargetA.r2_seventh_actual_orbit
#print axioms TargetA.r2_seventh_actual_real_orbit

#print axioms TargetA.r2_eighth_inverse_product
#print axioms TargetA.r2_eighth_actual_inverse
#print axioms TargetA.r2_eighth_actual_real_inverse
#print axioms TargetA.r2_eighth_transition_X
#print axioms TargetA.r2_eighth_transition_R
#print axioms TargetA.r2_eighth_transition_W
#print axioms TargetA.r2_eighth_transition_G
#print axioms TargetA.r2_eighth_transition_H
#print axioms TargetA.r2_eighth_transition_C
#print axioms TargetA.r2_eighth_recorded_transition
#print axioms TargetA.r2_eighth_actual_orbit
#print axioms TargetA.r2_eighth_actual_real_orbit

#print axioms TargetA.r2_ninth_inverse_product
#print axioms TargetA.r2_ninth_actual_inverse
#print axioms TargetA.r2_ninth_actual_real_inverse
#print axioms TargetA.r2_ninth_transition_X
#print axioms TargetA.r2_ninth_transition_R
#print axioms TargetA.r2_ninth_transition_W
#print axioms TargetA.r2_ninth_transition_G
#print axioms TargetA.r2_ninth_transition_H
#print axioms TargetA.r2_ninth_transition_C
#print axioms TargetA.r2_ninth_recorded_transition
#print axioms TargetA.r2_ninth_actual_orbit
#print axioms TargetA.r2_ninth_actual_real_orbit

#print axioms TargetA.r2_tenth_inverse_product
#print axioms TargetA.r2_tenth_actual_inverse
#print axioms TargetA.r2_tenth_actual_real_inverse
#print axioms TargetA.r2_tenth_transition_X
#print axioms TargetA.r2_tenth_transition_R
#print axioms TargetA.r2_tenth_transition_W
#print axioms TargetA.r2_tenth_transition_G
#print axioms TargetA.r2_tenth_transition_H
#print axioms TargetA.r2_tenth_transition_C
#print axioms TargetA.r2_tenth_recorded_transition
#print axioms TargetA.r2_tenth_actual_orbit
#print axioms TargetA.r2_tenth_actual_real_orbit

#eval do IO.println s!"RESOLVED_STEP10={← Lean.findOLean `TargetA.R2TenthStepCertificate}"

#print axioms TargetA.r2_eleventh_inverse_product
#print axioms TargetA.r2_eleventh_actual_inverse
#print axioms TargetA.r2_eleventh_actual_real_inverse
#print axioms TargetA.r2_eleventh_transition_X
#print axioms TargetA.r2_eleventh_transition_R
#print axioms TargetA.r2_eleventh_transition_W
#print axioms TargetA.r2_eleventh_transition_G
#print axioms TargetA.r2_eleventh_transition_H
#print axioms TargetA.r2_eleventh_transition_C
#print axioms TargetA.r2_eleventh_recorded_transition
#print axioms TargetA.r2_eleventh_actual_orbit
#print axioms TargetA.r2_eleventh_actual_real_orbit

#print axioms TargetA.r2_twelfth_inverse_product
#print axioms TargetA.r2_twelfth_actual_inverse
#print axioms TargetA.r2_twelfth_actual_real_inverse
#print axioms TargetA.r2_twelfth_transition_X
#print axioms TargetA.r2_twelfth_transition_R
#print axioms TargetA.r2_twelfth_transition_W
#print axioms TargetA.r2_twelfth_transition_G
#print axioms TargetA.r2_twelfth_transition_H
#print axioms TargetA.r2_twelfth_transition_C
#print axioms TargetA.r2_twelfth_recorded_transition
#print axioms TargetA.r2_twelfth_actual_orbit
#print axioms TargetA.r2_twelfth_actual_real_orbit

#print axioms TargetA.r2_thirteenth_inverse_product
#print axioms TargetA.r2_thirteenth_actual_inverse
#print axioms TargetA.r2_thirteenth_actual_real_inverse
#print axioms TargetA.r2_thirteenth_transition_X
#print axioms TargetA.r2_thirteenth_transition_R
#print axioms TargetA.r2_thirteenth_transition_W
#print axioms TargetA.r2_thirteenth_transition_G
#print axioms TargetA.r2_thirteenth_transition_H
#print axioms TargetA.r2_thirteenth_transition_C
#print axioms TargetA.r2_thirteenth_recorded_transition
#print axioms TargetA.r2_thirteenth_actual_orbit
#print axioms TargetA.r2_thirteenth_actual_real_orbit

#print axioms TargetA.r2_fourteenth_inverse_product
#print axioms TargetA.r2_fourteenth_actual_inverse
#print axioms TargetA.r2_fourteenth_actual_real_inverse
#print axioms TargetA.r2_fourteenth_transition_X
#print axioms TargetA.r2_fourteenth_transition_R
#print axioms TargetA.r2_fourteenth_transition_W
#print axioms TargetA.r2_fourteenth_transition_G
#print axioms TargetA.r2_fourteenth_transition_H
#print axioms TargetA.r2_fourteenth_transition_C
#print axioms TargetA.r2_fourteenth_recorded_transition
#print axioms TargetA.r2_fourteenth_actual_orbit
#print axioms TargetA.r2_fourteenth_actual_real_orbit

#eval do IO.println s!"RESOLVED_STEP14={← Lean.findOLean `TargetA.R2FourteenthStepCertificate}"
