#!/usr/bin/env python3
"""Standard-library-only exact checker for rho(M6)=10/3.

No LP/MILP optimizer, floating-point bound, or numerical tolerance is used.
Maximal independent sets are regenerated by a separate Bron-Kerbosch routine.
"""
from pathlib import Path
from fractions import Fraction
from collections import Counter
import json
P=Path(__file__).resolve().parent

def make_graph():
 adj=[2,1]
 for _ in range(4):
  n=len(adj);new=[0]*(2*n+1)
  for i in range(n):
   for j in range(n):
    if adj[i]>>j&1:
     new[i]|=(1<<j)|(1<<(n+j));new[n+i]|=1<<j
   new[n+i]|=1<<(2*n);new[2*n]|=1<<(n+i)
  adj=new
 return adj

def maximal_sets(adj):
 n=len(adj);full=(1<<n)-1;comp=[full^(a|(1<<i)) for i,a in enumerate(adj)];out=[]
 def visit(R,P,X):
  if not P and not X:out.append(R);return
  possible=P|X
  pivot=max((i for i in range(n) if possible>>i&1),key=lambda i:(P&comp[i]).bit_count())
  choices=P&~comp[pivot]
  while choices:
   bit=choices&-choices;choices^=bit;v=bit.bit_length()-1
   visit(R|bit,P&comp[v],X&comp[v]);P^=bit;X|=bit
 visit(0,full,0)
 assert len(out)==len(set(out))
 return sorted(out)

adj=make_graph();N=len(adj);ALL=(1<<N)-1
assert N==47 and all(not(a>>i&1) for i,a in enumerate(adj))
assert all(bool(adj[i]>>j&1)==bool(adj[j]>>i&1) for i in range(N) for j in range(N))
assert all(not(adj[i]&adj[j]) for i in range(N) for j in range(i) if adj[i]>>j&1),'Triangle found'
MIS=maximal_sets(adj)
stored=json.loads((P/'m6_candidates.json').read_text())
assert adj==stored['adj'] and MIS==stored['candidate_masks'] and len(MIS)==857
for mask in MIS:
 assert all(not(adj[i]&mask) for i in range(N) if mask>>i&1)
 assert all(adj[i]&mask for i in range(N) if not(mask>>i&1))

cert=json.loads((P/'upper_certificates.json').read_text())
assert cert['target_hall_ratio']==[10,3]
expected={str(k) for k in [1,3,4,5,6,7,8,9,10,11,12,13,14]}
assert set(cert['certificates'])==expected
stats=Counter()

def f(n,d):
 assert isinstance(n,int) and isinstance(d,int) and d>0
 return Fraction(n,d)

def check(node,k,target,ones=0,zeros=0):
 assert not(ones&zeros) and not((ones|zeros)&~ALL)
 stats['nodes']+=1;kind=node['type'];stats[kind]+=1
 free=ALL&~(ones|zeros)
 if kind=='split':
  v=node['vertex'];assert isinstance(v,int) and 0<=v<N and free>>v&1
  check(node['zero'],k,target,ones,zeros|(1<<v))
  check(node['one'],k,target,ones|(1<<v),zeros)
  return
 if kind=='conflict':
  j=node['row'];assert 0<=j<len(MIS) and (MIS[j]&ones).bit_count()>k
  return
 if kind=='trivial':
  assert free==0 and node['bound']==ones.bit_count()<target
  return
 assert kind=='dual'
 y={};z={}
 for j,num,den in node['y']:
  assert 0<=j<len(MIS) and j not in y
  y[j]=f(num,den);assert y[j]>=0
 for v,num,den in node['z']:
  assert 0<=v<N and free>>v&1 and v not in z
  z[v]=f(num,den);assert z[v]>=0
 for v in range(N):
  if free>>v&1:
   covered=sum((w for j,w in y.items() if MIS[j]>>v&1),Fraction(0))+z.get(v,Fraction(0))
   assert covered>=1
 upper=Fraction(ones.bit_count())+sum((w*(k-(MIS[j]&ones).bit_count()) for j,w in y.items()),Fraction(0))+sum(z.values(),Fraction(0))
 assert upper==f(*node['bound']) and upper<target

for kstr,entry in cert['certificates'].items():
 k=int(kstr);target=(10*k)//3+1
 assert entry['forbidden_size']==target
 before=stats['nodes'];check(entry['tree'],k,target)
 print(f'PASS exact upper: alpha <= {k} implies |S| <= {target-1}; nodes={stats["nodes"]-before}')
# Missing case k=2 uses the elementary R(3,3)=6 proof:
# any six vertices either contain three neighbors of a vertex (an independent
# triple in a triangle-free graph), or three nonneighbors; those nonneighbors
# contain a nonedge, which together with the vertex forms an independent triple.
# Thus alpha<=2 gives |S|<=5. For k>=15, |S|<=47<=(10/3)k.
assert Fraction(5,2)<=Fraction(10,3) and Fraction(47,15)<Fraction(10,3)

W=107765098387711
assert 0<W<=ALL and W.bit_count()==20
intersections=[(W&I).bit_count() for I in MIS]
alpha=max(intersections);assert alpha==6
maxset=W&MIS[intersections.index(alpha)]
assert maxset.bit_count()==6 and all(not(adj[i]&maxset) for i in range(N) if maxset>>i&1)
result={'status':'PASS','exact_hall_ratio':[10,3],'n':47,'maximal_independent_sets':857,'certificate_stats':dict(stats),'witness_mask':W,'witness_vertices':[i for i in range(N) if W>>i&1],'witness_independence_number':alpha,'maximum_independent_set_in_witness':[i for i in range(N) if maxset>>i&1],'arithmetic':'Python integers and fractions.Fraction; no optimization library imported'}
(P/'exact_certificate_check.json').write_text(json.dumps(result,indent=2)+'\n')
print('PASS: exact rho(M6)=10/3, matching upper certificate and 20-vertex alpha=6 witness')
print(json.dumps(result,indent=2))
