import Mathlib

namespace AMLStabilization

/-- The reciprocal energy with the linear drift removed. -/
noncomputable def reciprocalEnergyShift (c : ℝ) (E : ℝ → ℝ) (t : ℝ) : ℝ :=
  (E t)⁻¹ - c * t

/--
If a positive differentiable energy satisfies `E' + c E^2 ≤ 0`, then
`1/E - c t` is monotone.  This is the scalar calculus core behind the
quadratic-dissipation / algebraic-decay branch of the strengthened paper.
-/
theorem reciprocalEnergyShift_monotone
    {E dE : ℝ → ℝ} {c : ℝ}
    (hE : ∀ t, HasDerivAt E (dE t) t)
    (hpos : ∀ t, 0 < E t)
    (hdiss : ∀ t, dE t + c * E t ^ 2 ≤ 0) :
    Monotone (reciprocalEnergyShift c E) := by
  refine monotone_of_hasDerivAt_nonneg
    (f' := fun t => -dE t / E t ^ 2 - c) ?_ ?_
  · intro t
    unfold reciprocalEnergyShift
    have hinv := (hE t).inv (ne_of_gt (hpos t))
    have hlin : HasDerivAt (fun x : ℝ => c * x) c t :=
      hasDerivAt_const_mul c
    simpa using hinv.sub hlin
  · intro t
    have hsq : 0 < E t ^ 2 := by positivity
    have hcdiv : c ≤ -dE t / E t ^ 2 := by
      rw [le_div_iff₀ hsq]
      linarith [hdiss t]
    linarith

/-- Reciprocal lower bound generated by quadratic energy dissipation. -/
theorem reciprocalEnergy_lower_of_quadratic_dissipation
    {E dE : ℝ → ℝ} {c s t : ℝ}
    (hE : ∀ τ, HasDerivAt E (dE τ) τ)
    (hpos : ∀ τ, 0 < E τ)
    (hdiss : ∀ τ, dE τ + c * E τ ^ 2 ≤ 0)
    (hst : s ≤ t) :
    1 / E s + c * (t - s) ≤ 1 / E t := by
  have hmono := reciprocalEnergyShift_monotone hE hpos hdiss
  have h := hmono hst
  dsimp [reciprocalEnergyShift] at h
  simpa [one_div] using (show (E s)⁻¹ + c * (t - s) ≤ (E t)⁻¹ by linarith)

/--
Explicit inverse-linear bound for a positive energy satisfying
`E' + c E^2 ≤ 0` with `c ≥ 0`.
-/
theorem energy_le_inverse_linear_of_quadratic_dissipation
    {E dE : ℝ → ℝ} {c s t : ℝ}
    (hE : ∀ τ, HasDerivAt E (dE τ) τ)
    (hpos : ∀ τ, 0 < E τ)
    (hc : 0 ≤ c)
    (hdiss : ∀ τ, dE τ + c * E τ ^ 2 ≤ 0)
    (hst : s ≤ t) :
    E t ≤ E s / (1 + c * E s * (t - s)) := by
  have hrec := reciprocalEnergy_lower_of_quadratic_dissipation hE hpos hdiss hst
  have hdt : 0 ≤ t - s := sub_nonneg.mpr hst
  have hden : 0 < 1 + c * E s * (t - s) := by positivity
  have hcandidate : 0 < E s / (1 + c * E s * (t - s)) :=
    div_pos (hpos s) hden
  apply le_of_one_div_le_one_div hcandidate
  calc
    1 / (E s / (1 + c * E s * (t - s))) =
        1 / E s + c * (t - s) := by
          field_simp [ne_of_gt (hpos s), ne_of_gt hden]
          ring
    _ ≤ 1 / E t := hrec

/--
A quartic weighted-coercivity shape `E ≤ Γ sqrt(D)` implies the algebraic
relation `E^2 ≤ Γ^2 D`.
-/
theorem quarticCoercivity_to_quadraticDissipation
    {E D Γ : ℝ}
    (hE0 : 0 ≤ E) (hD0 : 0 ≤ D) (hΓ0 : 0 ≤ Γ)
    (hcoerc : E ≤ Γ * Real.sqrt D) :
    E ^ 2 ≤ Γ ^ 2 * D := by
  have hrhs : 0 ≤ Γ * Real.sqrt D := mul_nonneg hΓ0 (Real.sqrt_nonneg _)
  have hsq := (sq_le_sq₀ hE0 hrhs).2 hcoerc
  calc
    E ^ 2 ≤ (Γ * Real.sqrt D) ^ 2 := hsq
    _ = Γ ^ 2 * D := by rw [mul_pow, Real.sq_sqrt hD0]

/--
Representative `q=4` rate theorem.  If the energy is controlled by the square
root of the dissipation and the PDE energy identity gives `E' + 2D ≤ 0`, then
the positive branch decays at an explicit inverse-linear rate.
-/
theorem quarticDamping_to_inverseLinearEnergyDecay
    {E dE D : ℝ → ℝ} {Γ s t : ℝ}
    (hEderiv : ∀ τ, HasDerivAt E (dE τ) τ)
    (hEpos : ∀ τ, 0 < E τ)
    (hD : ∀ τ, 0 ≤ D τ)
    (hΓ : 0 < Γ)
    (hcoerc : ∀ τ, E τ ≤ Γ * Real.sqrt (D τ))
    (henergy : ∀ τ, dE τ + 2 * D τ ≤ 0)
    (hst : s ≤ t) :
    E t ≤ E s / (1 + (2 / Γ ^ 2) * E s * (t - s)) := by
  have hΓ0 : 0 ≤ Γ := le_of_lt hΓ
  have hΓsq : 0 < Γ ^ 2 := by positivity
  have hdiss : ∀ τ, dE τ + (2 / Γ ^ 2) * E τ ^ 2 ≤ 0 := by
    intro τ
    have hquad := quarticCoercivity_to_quadraticDissipation
      (hE0 := le_of_lt (hEpos τ)) (hD0 := hD τ) hΓ0 (hcoerc τ)
    have hscaled : (2 / Γ ^ 2) * E τ ^ 2 ≤ 2 * D τ := by
      rw [div_mul_eq_mul_div, div_le_iff₀ hΓsq]
      nlinarith
    linarith [henergy τ]
  exact energy_le_inverse_linear_of_quadratic_dissipation
    hEderiv hEpos (by positivity) hdiss hst

/-- Cubically degenerate kinetics have exact quartic dissipation. -/
theorem cubicDegenerateIdentity (κ s vstar : ℝ) :
    (s - vstar) * (-κ * (s - vstar) ^ 3) =
      -κ * (s - vstar) ^ 4 := by
  ring

end AMLStabilization
