import Mathlib
import AMLStabilization.BoxSignalEnergyCore
import AMLStabilization.EnergyDifferentiationCore

open Set Finset MeasureTheory Filter
open scoped Topology

namespace AMLStabilization

/--
Time-dependent rectangular-box signal energy endpoint.  The energy derivative
is no longer supplied as an external identity: it is generated by dominated
differentiation of `∫ w(t,x)^2`, then fed directly into the pointwise-PDE/Green
box estimate.
-/
theorem timeDependentBoxSignalEnergyInequality_q
    {n : ℕ}
    {a b : Fin (n + 1) → ℝ}
    (hle : a ≤ b)
    (u w wt R : ℝ → (Fin (n + 1) → ℝ) → ℝ)
    (dw : ℝ → (Fin (n + 1) → ℝ) →
      (Fin (n + 1) → ℝ) →L[ℝ] ℝ)
    (dgrad : ℝ → (Fin (n + 1) → ℝ) → Fin (n + 1) →
      (Fin (n + 1) → ℝ) →L[ℝ] ℝ)
    (bad : Set (Fin (n + 1) → ℝ))
    {t0 beta q : ℝ} {s : Set ℝ}
    {bound : (Fin (n + 1) → ℝ) → ℝ}
    (hu : ∀ x, 0 ≤ u t0 x)
    (hpoint : ∀ x,
      w t0 x * R t0 x ≤ -beta * |w t0 x| ^ q)
    (hPDE : ∀ x,
      wt t0 x = derivativeTraceLaplacian (dgrad t0) x +
        u t0 x * R t0 x)
    (hs : s ∈ 𝓝 t0)
    (hSquareMeas : ∀ᶠ t in 𝓝 t0,
      AEStronglyMeasurable (fun x => w t x ^ 2)
        (volume.restrict (Icc a b)))
    (hSquareInt : Integrable (fun x => w t0 x ^ 2)
      (volume.restrict (Icc a b)))
    (hDerivMeas : AEStronglyMeasurable
      (fun x => 2 * w t0 x * wt t0 x)
      (volume.restrict (Icc a b)))
    (hDerivBound : ∀ᵐ x ∂(volume.restrict (Icc a b)),
      ∀ t ∈ s, ‖2 * w t x * wt t x‖ ≤ bound x)
    (hBoundInt : Integrable bound (volume.restrict (Icc a b)))
    (hTimeDeriv : ∀ᵐ x ∂(volume.restrict (Icc a b)),
      ∀ t ∈ s, HasDerivAt (fun tau => w tau x) (wt t x) t)
    (hreaction : IntegrableOn
      (fun x => u t0 x * (w t0 x * R t0 x)) (Icc a b))
    (hweighted : IntegrableOn
      (fun x => u t0 x * |w t0 x| ^ q) (Icc a b))
    (hbad : bad.Countable)
    (hwcont : ContinuousOn (w t0) (Icc a b))
    (hgradcont : ∀ i, ContinuousOn
      (fun x => derivativeCoordinateGradient (dw t0) x i) (Icc a b))
    (hwdiff : ∀ x,
      x ∈ (Set.pi Set.univ fun i => Ioo (a i) (b i)) \ bad →
      HasFDerivAt (w t0) (dw t0 x) x)
    (hgradDiff : ∀ x,
      x ∈ (Set.pi Set.univ fun i => Ioo (a i) (b i)) \ bad →
      ∀ i, HasFDerivAt
        (fun y => derivativeCoordinateGradient (dw t0) y i)
        (dgrad t0 x i) x)
    (hfront : ∀ i (x : Fin n → ℝ),
      derivativeCoordinateGradient (dw t0) (i.insertNth (b i) x) i = 0)
    (hback : ∀ i (x : Fin n → ℝ),
      derivativeCoordinateGradient (dw t0) (i.insertNth (a i) x) i = 0)
    (hGradInt : IntegrableOn
      (fun x => ∑ i : Fin (n + 1),
        (derivativeCoordinateGradient (dw t0) x i) ^ 2) (Icc a b))
    (hWLapInt : IntegrableOn
      (fun x => w t0 x * derivativeTraceLaplacian (dgrad t0) x)
      (Icc a b)) :
    HasDerivAt
      (fun t => ∫ x in Icc a b, w t x ^ 2)
      (2 * ∫ x in Icc a b, w t0 x * wt t0 x) t0 ∧
    (2 * ∫ x in Icc a b, w t0 x * wt t0 x) +
      2 *
        ((∫ x in Icc a b,
            ∑ i : Fin (n + 1),
              (derivativeCoordinateGradient (dw t0) x i) ^ 2) +
          beta * (∫ x in Icc a b, u t0 x * |w t0 x| ^ q)) ≤ 0 := by
  let mu : Measure (Fin (n + 1) → ℝ) := volume.restrict (Icc a b)
  have hderivMu := hasDerivAt_integral_square_of_dominated
    (mu := mu) (w := w) (wt := wt) (t0 := t0)
    (s := s) (bound := bound)
    hs
    (by simpa [mu] using hSquareMeas)
    (by simpa [mu] using hSquareInt)
    (by simpa [mu] using hDerivMeas)
    (by simpa [mu] using hDerivBound)
    (by simpa [mu] using hBoundInt)
    (by simpa [mu] using hTimeDeriv)
  have hderiv :
      HasDerivAt
        (fun t => ∫ x in Icc a b, w t x ^ 2)
        (2 * ∫ x in Icc a b, w t0 x * wt t0 x) t0 := by
    simpa [mu] using hderivMu
  have hineq := boxSignalEnergyInequality_q_from_pointwisePDE
    hle (u t0) (w t0) (wt t0) (R t0)
    (dw t0) (dgrad t0) bad
    (dE := 2 * ∫ x in Icc a b, w t0 x * wt t0 x)
    (beta := beta) (q := q)
    hu hpoint hPDE rfl
    hreaction hweighted hbad hwcont hgradcont hwdiff hgradDiff
    hfront hback hGradInt hWLapInt
  exact ⟨hderiv, hineq⟩

end AMLStabilization
